name: "release [NOT FUNCTIONAL]"

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup .npmrc
        run: |
          npm config set @gdagosto:registry "https://npm.pkg.github.com/"
          npm config set //npm.pkg.github.com/:_authToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-nm-install

      - run: pnpm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
